// 389. Find the Difference
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.
// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

// class Solution {
//   String findTheDifference(String s, String t) {
//     Map<String, int> frequency = {};
//     for (int i = 0; i < s.length; i++) {
//       frequency[s[i]] = (frequency[s[i]] ?? 0) + 1;
//     }
//     for (int i = 0; i < t.length; i++) {
//       if (frequency.containsKey(t[i])) {
//         frequency[t[i]] = (frequency[t[i]] ?? 0) - 1 as int;
//       } else {
//         frequency[t[i]] = -1;
//       }
//     }
//     for (String key in frequency.keys) {
//       if (frequency[key] == -1) {
//         return key;
//       }
//     }
//     return "";
//   }
// }

class Solution {
  String findTheDifference(String s, String t) {
    int sum1 = 0;
    int sum2 = 0;
    int i;
    for (i = 0; i < s.length; i++) {
      sum1 += s.codeUnitAt(i);
      sum2 += t.codeUnitAt(i);
    }
    sum2 += t.codeUnitAt(i);
    return String.fromCharCode(sum2 - sum1);
  }
}

void main() {
  Solution solution = Solution();
  String s = "abcd";
  String t = "abcde";

  String result = solution.findTheDifference(s, t);
  print(result);
}
